root: true
env:
  browser: true
  es2021: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser',
  project: ./tsconfig.json
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
extends:
  - '@vue/typescript'
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
  - '@typescript-eslint'